name: "Issue Workflow"
on:
  issues:
    types:
      - opened
jobs:
  issue_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger when issues come
        run: echo "Workflow run on opening of issue"
