name: "MULTI EVENT"
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
jobs:
  multi_events_flow:
    runs-on: ubuntu-latest
    steps:
      - name: "Multi Events Step"
        run: echo "multi events workflow"
